config/routes.rb
Rails.application.routes.draw do
  resources :character_builder, only: %i(index create) do
    collection do
      get :calculated
    end
  end
end

app/models/attack/base.rb
module Attack
  class Base
    def self.type
      'physical'
    end

    def self.damage
      1
    end

    def self.speed
      1
    end
  end
end

app/models/attack/cleave.rb
module Attack
  class Cleave < Base
    def self.type
      'cold'
    end

    def self.damage
      1.2
    end

    def self.speed
      0.9
    end
  end
end

app/models/attack/punch.rb
module Attack
  class Punch < Base
  end
end

app/models/attack/smite.rb
module Attack
  class Smite < Base
    def self.type
      'fire'
    end

    def self.damage
      0.9
    end

    def self.speed
      1.2
    end
  end
end

app/models/character.rb
class Character
  attr_reader :level

  def initialize(level)
    @level = level
  end

  def vitality
    level * 5
  end

  def strength
    level * 10
  end
end

app/models/weapon/axe.rb
module Weapon
  class Axe < Base
    def self.min_dmg
      50
    end

    def self.max_dmg
      65
    end

    def self.element
      'fire'
    end

    def self.ele_mod
      1.10
    end

    def self.str_mod
      20
    end

    def self.speed
      1.2
    end
  end
end

app/models/weapon/base.rb
module Weapon
  class Base
    def self.min_dmg
      0
    end

    def self.max_dmg
      0
    end

    def self.element
      ''
    end

    def self.ele_mod
      1
    end

    def self.str_mod
      0
    end

    def self.speed
      1
    end
  end
end

app/models/weapon/mace.rb
module Weapon
  class Mace < Base
    def self.min_dmg
      60
    end

    def self.max_dmg
      75
    end

    def self.element
      'cold'
    end

    def self.ele_mod
      1.10
    end

    def self.str_mod
      20
    end
  end
end

app/models/weapon/sword.rb
module Weapon
  class Sword < Base
    def self.min_dmg
      40
    end

    def self.max_dmg
      55
    end

    def self.str_mod
      20
    end

    def self.speed
      1.4
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/character_builder_controller.rb
class CharacterBuilderController < ApplicationController
  def index
    @attacks = Weapon::Base.descendants.each_with_object({}) do |weapon, hash|
      hash[weapon.name.demodulize] = weapon
    end
  end

  def create
    redirect_to calculated_character_builder_index_path(permitted_params)
  end

  def calculated
  end

  private

  def permitted_params
    params.permit(:char_level, :weap_type)
        .merge(params.fetch(:damage, {})
                   .permit(Cleave: [:dps, :max_dmg, :min_dmg],
                           Punch: [:dps, :max_dmg, :min_dmg],
                           Smite: [:dps, :max_dmg, :min_dmg]))
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/character_builder/calculated.html.slim
- total_damage = CalculateDamage.new(params[:char_level].to_i, params[:weap_type]).calculate

.full-width.flex.ai-c.jc-c.mt-4
  .mt-4.border-full.border-color-ltcyan.c-offwhite-100.bg-daggergray-100.p-1
    h3
      'Your possible damage is:
    .flex style='width: 650px'
      table
        thead
          tr
            th.py-1 Attack Type
            th.py-1  Min Damage
            th.py-1  Max Damage
            th.py-1  DPS
        tbody
          - total_damage.each do |damage|
            tr
              td.p-1 = damage[:name]
              td.p-1 = damage[:min_dmg]
              td.p-1 = damage[:max_dmg]
              td.p-1 = damage[:dps]
      .male-warrior style='background-image: url(/assets/male_warrior.png)'

    = link_to character_builder_index_path
      button
        'Back

app/views/character_builder/index.html.slim
.full-width.flex.ai-c.jc-c.mt-4
  .mt-4.border-full.border-color-ltcyan.c-offwhite-100.bg-daggergray-100.p-1
    h3.text-center
      'Welcome to the RPG damage calculator!
    .mt-1.text-center
      'Gimme your character and weapon and I'll work my magic
    .flex.jc-c
      .female-warrior style='background-image: url(/assets/female_warrior_cropped.png)'
      = form_tag class: 'mt-3 flex fd-c jc-fe ai-fe'
        .flex.fd-c.jc-c.mt-1
          div
            = label_tag :character_level
            div
              = number_field_tag :char_level, nil, within: 1...91, required: true
          .mt-2
            = label_tag :weapon_type
            div
              = select_tag :weap_type, options_for_select(@attacks), include_blank: true, required: true
          .mt-2
            = submit_tag 'Do The Magic'

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="banner-image" style='background-image: url(/assets/bg_tile.png)'>
  <head>
    <style>
      html {
        font-family: garamond, arial, sans-serif;
      }
    </style>
    <title>CopycatGaming</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>